import type { WorkspaceData } from "./domain";
export const demoToday = "2026-09-14";
const silangId = "11111111-1111-4111-8111-111111111111";
const silangOldId = "33333333-3333-4333-8333-333333333333";
const carmonaId = "22222222-2222-4222-8222-222222222222";
export const demoData: WorkspaceData = {
  organizations: [
    {
      id: silangId,
      name: "Southwoods Silang Bayan",
      currency: "PHP",
      address: "Silang Bayan Service Center, Cavite, Philippines",
      tax_id: "TIN 000-000-000-000",
      contact_email: "silang.bayan@southwoods.example",
      contact_phone: "+63 46 800 0101",
    },
    {
      id: silangOldId,
      name: "Southwoods Silang Old",
      currency: "PHP",
      address: "Silang Old Service Center, Cavite, Philippines",
      tax_id: "TIN 000-000-000-002",
      contact_email: "silang.old@southwoods.example",
      contact_phone: "+63 46 800 0103",
    },
    {
      id: carmonaId,
      name: "Southwoods Carmona",
      currency: "PHP",
      address: "Carmona Service Center, Cavite, Philippines",
      tax_id: "TIN 000-000-000-001",
      contact_email: "carmona@southwoods.example",
      contact_phone: "+63 46 800 0102",
    },
  ],
  subscribers: [
    {
      id: "s1",
      organization_id: silangId,
      account_number: "RL-001001",
      name: "Alex Rivera",
      email: "alex@example.com",
      phone: "+63 917 555 0101",
      address: "San Isidro · North branch",
      status: "active",
    },
    {
      id: "s2",
      organization_id: silangId,
      account_number: "RL-001002",
      name: "Mika Santos",
      email: "mika@example.com",
      phone: "+63 917 555 0102",
      address: "Poblacion · Central branch",
      status: "active",
    },
    {
      id: "s3",
      organization_id: silangOldId,
      account_number: "RL-001003",
      name: "Jamie Cruz",
      email: "jamie@example.com",
      phone: "+63 917 555 0103",
      address: "San Roque · North branch",
      status: "suspended",
    },
    {
      id: "s4",
      organization_id: carmonaId,
      account_number: "RL-001004",
      name: "Robin Garcia",
      email: "robin@example.com",
      phone: "+63 917 555 0104",
      address: "Mabini · Central branch",
      status: "active",
    },
    {
      id: "s5",
      organization_id: carmonaId,
      account_number: "RL-001005",
      name: "Casey Reyes",
      email: "casey@example.com",
      phone: "+63 917 555 0105",
      address: "San Isidro · North branch",
      status: "pending",
    },
    {
      id: "s6",
      organization_id: carmonaId,
      account_number: "RL-001006",
      name: "Taylor Dela Rosa",
      email: "taylor@example.com",
      phone: "+63 917 555 0106",
      address: "Poblacion · Central branch",
      status: "active",
    },
  ],
  plans: [
    {
      id: "p1",
      organization_id: silangId,
      name: "Fiber Essential",
      download_mbps: 100,
      upload_mbps: 100,
      price_minor: 129900,
      currency: "PHP",
    },
    {
      id: "p2",
      organization_id: silangId,
      name: "Fiber Plus",
      download_mbps: 300,
      upload_mbps: 300,
      price_minor: 189900,
      currency: "PHP",
    },
    {
      id: "p3",
      organization_id: silangOldId,
      name: "Fiber Pro",
      download_mbps: 600,
      upload_mbps: 600,
      price_minor: 249900,
      currency: "PHP",
    },
    {
      id: "p4",
      organization_id: carmonaId,
      name: "Fiber Essential",
      download_mbps: 100,
      upload_mbps: 100,
      price_minor: 129900,
      currency: "PHP",
    },
    {
      id: "p5",
      organization_id: carmonaId,
      name: "Fiber Plus",
      download_mbps: 300,
      upload_mbps: 300,
      price_minor: 189900,
      currency: "PHP",
    },
    {
      id: "p6",
      organization_id: carmonaId,
      name: "Fiber Pro",
      download_mbps: 600,
      upload_mbps: 600,
      price_minor: 249900,
      currency: "PHP",
    },
  ],
  services: [
    { id: "v1", organization_id: silangId, subscriber_id: "s1", plan_id: "p2", status: "active" },
    { id: "v2", organization_id: silangId, subscriber_id: "s2", plan_id: "p1", status: "active" },
    { id: "v3", organization_id: silangOldId, subscriber_id: "s3", plan_id: "p3", status: "suspended" },
    { id: "v4", organization_id: carmonaId, subscriber_id: "s4", plan_id: "p6", status: "active" },
    { id: "v6", organization_id: carmonaId, subscriber_id: "s6", plan_id: "p4", status: "active" },
  ],
  invoices: [
    {
      id: "i1",
      organization_id: silangId,
      number: "INV-2026-0091",
      subscriber_id: "s1",
      issued_on: "2026-09-01",
      due_on: "2026-09-20",
      description: "Fiber Plus monthly service — September 2026",
      total_minor: 189900,
      paid_minor: 0,
      currency: "PHP",
    },
    {
      id: "i2",
      organization_id: silangId,
      number: "INV-2026-0092",
      subscriber_id: "s2",
      issued_on: "2026-09-01",
      due_on: "2026-09-10",
      description: "Fiber Essential monthly service — September 2026",
      total_minor: 129900,
      paid_minor: 129900,
      currency: "PHP",
    },
    {
      id: "i3",
      organization_id: silangOldId,
      number: "INV-2026-0083",
      subscriber_id: "s3",
      issued_on: "2026-08-01",
      due_on: "2026-08-20",
      description: "Fiber Plus monthly service — August 2026",
      total_minor: 189900,
      paid_minor: 0,
      currency: "PHP",
    },
    {
      id: "i4",
      organization_id: carmonaId,
      number: "INV-2026-0094",
      subscriber_id: "s4",
      issued_on: "2026-09-01",
      due_on: "2026-09-10",
      description: "Fiber Pro monthly service — September 2026",
      total_minor: 249900,
      paid_minor: 100000,
      currency: "PHP",
    },
    {
      id: "i6",
      organization_id: carmonaId,
      number: "INV-2026-0096",
      subscriber_id: "s6",
      issued_on: "2026-09-01",
      due_on: "2026-09-10",
      description: "Fiber Essential monthly service — September 2026",
      total_minor: 129900,
      paid_minor: 129900,
      currency: "PHP",
    },
  ],
  payments: [
    { id: "pay1", organization_id: silangId, subscriber_id: "s2", reference: "GCASH-804219", receipt_number: "OR-2026-000091", payment_method: "GCash", amount_minor: 129900, currency: "PHP", received_at: "2026-09-09T08:30:00Z" },
    { id: "pay2", organization_id: carmonaId, subscriber_id: "s4", reference: "BANK-150882", receipt_number: "OR-2026-000092", payment_method: "Bank transfer", amount_minor: 100000, currency: "PHP", received_at: "2026-09-10T04:12:00Z" },
    { id: "pay3", organization_id: carmonaId, subscriber_id: "s6", reference: "CASH-0096", receipt_number: "OR-2026-000093", payment_method: "Cash", amount_minor: 129900, currency: "PHP", received_at: "2026-09-10T09:05:00Z" },
  ],
  allocations: [
    { id: "pa1", organization_id: silangId, invoice_id: "i2", payment_id: "pay1", amount_minor: 129900 },
    { id: "pa2", organization_id: carmonaId, invoice_id: "i4", payment_id: "pay2", amount_minor: 100000 },
    { id: "pa3", organization_id: carmonaId, invoice_id: "i6", payment_id: "pay3", amount_minor: 129900 },
  ],
  networkIdentities: [],
  audit: [
    {
      id: "a1",
      organization_id: silangId,
      action: "subscriber.created",
      entity_type: "subscribers",
      created_at: "2026-09-14T08:40:00Z",
    },
    {
      id: "a2",
      organization_id: carmonaId,
      action: "plan.created",
      entity_type: "plans",
      created_at: "2026-09-14T08:10:00Z",
    },
  ],
};
